### ISSUE TITLE
GTM google tag assistant is not connecting

### ISSUE THREAD

**Issue by RenuSuresh** [superside-oss/partytown-gtm-plugin#4]
@slawekkolodziej Thanks for the solve https://github.com/superside-oss/partytown-gtm-plugin/issues/3 for issue earlier that we were facing.
I have installed the new version, and we were not getting any error on the console or the postMessage error, but GTM is not connecting. 

repo : https://github.com/RenuSuresh/next-spofity

I have deployed the changes here. https://main--visionary-daifuku-766501.netlify.app/, however it is not connecting locally as well.
Could you please help.

**Comment by slawekkolodziej** [comment]
I looked at the code in the linked repository. It seems that the issue is on your side. You did not follow setup instructions described in the README file. Your code injects GTM snippet through plain `<script type="text/partytown">` but it should use provided `<GTMScript>` component.
