### ISSUE TITLE
Could not able to connect to Google Tag Assistant in GTM and it shows no tags found

### ISSUE THREAD

**Issue by maruthasalamr** [superside-oss/partytown-gtm-plugin#7]
Added partytown to my gtm script i could not able to debug/tests the events are firing and tracking in GTM. After lots of research so i came to know this component is helping to debugg

After installing the @superside-oss/partytown-gtm and followed the steps as per documentation. Still i could not able to see the tags in Google tag Assistant. please help on this @slawekkolodziej 

React code in header component

`<---Head Tag -->
<Partytown
        forward={[
          'dataLayer.push',
          GTM_TAG_ASSISTANT_FORWARDER
        ]}
        mainWindowAccessors={[
          GTM_TAG_ASSISTANT_ACCESSOR
        ]}
        resolveUrl={partytownResolveUrl}
      />
      <GTMScript gtmId={'GTM-MKPX3TV4' as string} />
   <--- Body Tag --->
   <Partytown debug={true} forward={['dataLayer.push','gtag']}>
      <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MKPX3TV4" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
      </Partytown>`
      
      
<img width="890" alt="image" src="https://github.com/superside-oss/partytown-gtm-plugin/assets/78694065/9faec53f-967f-4d46-8438-5aaa0a76f9f3">

**Comment by slawekkolodziej** [comment]
You have two `<Partytown>` components in your code snippet. This isn't right. Do you see any errors in network tab?
I highly doubt it's a bug in the library. Try checking out this repo and trying with the provided NextJS sample app.

**Comment by maruthasalamr** [comment]
yes, for head tag and body tag is there,
so i have added partytown component to both script tags
<img width="810" alt="image" src="https://github.com/superside-oss/partytown-gtm-plugin/assets/78694065/1ee15079-b99c-4028-9de4-c064aed94d2e">

Tech Stack
I'm React gatsby for frontend and using helmet to load all the script tags

**Comment by maruthasalamr** [comment]
I'm using partytown-gtm-plugin to debug the Google tag manager using partytown. Here is my implemented code. Still  i could not able to debug/tests the events are firing and tracking in GTM. @slawekkolodziej please help me on this.

 "@superside-oss/partytown-gtm": "^1.0.0-alpha.12"
  "@builder.io/partytown": "^0.9.2"

` <PageContext.Provider value={{ pathPrefixes, websiteLocale }}>
      <Helmet>
        <Partytown
          forward={['dataLayer.push', GTM_TAG_ASSISTANT_FORWARDER]}
          mainWindowAccessors={[GTM_TAG_ASSISTANT_ACCESSOR]}
          resolveUrl={partytownResolveUrl}
        />
        <GTMScript gtmId={'GTM-MKPX3TV4' as string} />

        <link rel="preconnect" href="https://mktmediadev.wallstreetenglish.com" />
        <link rel="dns-prefetch" href="https://mktmediadev.wallstreetenglish.com" />

      </Helmet>

      <Header
        websiteLocale={websiteLocale}
        isInternationalSite={website.settings?.isInternationalSite ?? false}
        pathPrefixes={pathPrefixes}
        id={website.id}
        availableRoutes={availableRoutes}
      />
      <div id="main-root">{children}</div>
      <Footer websiteLocale={websiteLocale} />
   
    </PageContext.Provider>`
    
<img width="804" alt="image" src="https://github.com/superside-oss/partytown-gtm-plugin/assets/78694065/d826b9fb-623e-400a-bcc8-b43c2b53488f">

**Comment by slawekkolodziej** [comment]
It's not how you're supposed to use Partytown. `<Partytown>` should appear only once in your document. Same for `<GTMScript>`. Go ahead and review a sample NextJS app here: https://github.com/superside-oss/partytown-gtm-plugin/tree/alpha/packages/integration/nextjs
Also you should set up server-side proxy for assets that misses CORS headers. GTM won't work without it.

I am closing this issue as it does not look like a bug in the library.

**Comment by maruthasalamr** [comment]
I does not receive any CORS error in network tab.

I will followup the docs which you shared. thank you for your support

**Comment by maruthasalamr** [comment]
do you have any example to setup server side proxy for Gatsby

**Comment by slawekkolodziej** [comment]
Nope, I did not work with Gatsby for years.
